language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: reservation-bot-j
  api_key:
    secure: Dh28ba5gxXahJTp4oOkPPp7SAxvpthkAj8YI2DnGx+NY9j4N9M/4pPZIu6lg1nD3ci3TX9K9Ttzrf92hpHG0WtPtlfs/IOZZDAlpyklNg/1E37ONw5E+N6RF2MT2/gXpt80lDObJ1rW6zA1qyHR3N+9ncY6PNOgwgi9BcZB32+bQ8uli16KTEw+q6i0IbfTxnytfS+FoQZiyehV3LzYFKh18iC7DM5CLW5JChRlBK/oXHl7AAA8ttv55ZcIDCkj8l2v9r2re4eq934hXwRbQLVCQzH8AX52RJcylKv0ukr1RZ7m3FlBYT1/j7tzv8jQyTT0t/yJafFMoHLRxkF1Bz6v4yBH06lJfP+mGoubTcVn9DB6/NbS9cINFF9JWVZK22jGjVfvB6SSgXjZK0fK906iGYjvp6jadW5cJ49WRgBWxifnD3AXuzrkRYa669KQi2m++DZG9PhR780ZSkAduGPIp7VUoaZyx9WAlf81sYlv7+iQIPdFZJM304E7udtSxf6USNJfCAtF7FoZIwZ1rXDNIZzBGFHVzJ1ADABYKSWfRaHR+JZ7CAPHB5QpHfHpAt+mA2IUojAtrcXeAL1T2vPHB2NYwnoafq1DUmjJ7F08CFYQhH8qpmK09pvZeOI3Xm1aBmkXGx8ScB2N0hHoE3izyODqHdJr7+Eu7gd2JKL8=
